# Generated by Django 3.0.14 on 2024-02-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sales_data1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mail_id', models.CharField(max_length=30)),
                ('mobile_no', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
    ]
