# Generated by Django 3.0.14 on 2024-02-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_auto_20240205_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_data1',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='sales_data1',
            name='last_name',
        ),
    ]
