# Generated by Django 3.0.14 on 2024-02-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_auto_20240205_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_data1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('gst_number', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('product_number', models.IntegerField()),
                ('product_Price', models.IntegerField()),
            ],
        ),
    ]
