# Generated by Django 3.0.14 on 2024-02-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0004_seller_data1'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_data1',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
