# Generated by Django 3.0.14 on 2024-02-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_sales_data1_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sales_data1',
        ),
    ]
