# Generated by Django 3.0.14 on 2024-02-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0006_delete_sales_data1'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_data1',
            name='shopname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
